name: Add new issues to Ignite GH Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      id-token: write
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT }}

  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Label issue
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_LABEL: ${{ secrets.ISSUE_LABEL }}
        run: |
          gh issue edit $ISSUE_NUMBER --add-label "$ISSUE_LABEL" --repo ${{ github.repository }}